version: "3.10"
services:
  worker:
    build: .
    environment:
      - bot_token=${bot_token}
      - API_KEY=${API_KEY}
      - BOT_TOKEN=${BOT_TOKEN}
      - WORKERS=${WORKERS}
      - CHANNEL_URL=${CHANNEL_URL}
      - BOT_URL=${BOT_URL}
